version: '3.8'

services:
  backend:
    build: .
    command: uvicorn app.backend:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    env_file:
      - .env

  frontend:
    build: .
    command: streamlit run app/frontend.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    depends_on:
      - backend